### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'view'

### ISSUE THREAD

**Issue by ZPzhu** [gafniguy/4D-Facial-Avatars#24]
when I run train_transformed_rays.py,the error occur.And the argument ray_directions_ablation in train_utils.py is None,but the function in  train_transformed_rays.py does not have the correspond input.
thanks.

**Comment by StephenCha** [comment]
I'm not the author, but I solved the problem.
The link would be helpful to you: https://github.com/gafniguy/4D-Facial-Avatars/issues/16#issuecomment-1030278405
After doing this, there are no errors related to the ablation study.

**Comment by ZPzhu** [comment]
> I'm not the author, but I solved the problem. The link would be helpful to you: [#16 (comment)](https://github.com/gafniguy/4D-Facial-Avatars/issues/16#issuecomment-1030278405) After doing this, there are no errors related to the ablation study.

Thanks very much. I added the input ray_directions_ablation=ray_directions.The problem is solved temporarily.

**Comment by overoverlord** [comment]
> > > 我不是作者，但解决了这个问题。该链接后自动错误[评论，我没有帮助：#16](https://github.com/gafniguy/4D-Facial-Avatars/issues/16#issuecomment-1030278405)执行此操作与消融研究相关的。
> > 
> > 
> > 非常感谢。我添加了输入ray_directions_ablation=ray_directions。暂时解决了问题。
> 
> In which line or file did you add this line of input? I also encountered this problem
> 
> Traceback (most recent call last): File "K:\GAN\4D-Facial-Avatars-main\nerface_code\nerf-pytorch\train_transformed_rays.py", line 602, in main() File "K:\GAN\4D-Facial-Avatars-main\nerface_code\nerf-pytorch\train_transformed_rays.py", line 336, in main rgb_coarse, _, _, rgb_fine, _, _, weights = run_one_iter_of_nerf( File "K:\GAN\4D-Facial-Avatars-main\nerface_code\nerf-pytorch\nerf\train_utils.py", line 206, in run_one_iter_of_nerf rd_ablations = ray_directions_ablation.view((-1, 3)) AttributeError: 'NoneType' object has no attribute 'view'

He was mentioning the file "nerface_code/nerf-pytorch/nerf/train_utils.py". But actually I do not think it is a good idea to "added the input ray_directions_ablation=ray_directions". It is better to follow the author's suggestion in #16 that commenting all the code with "ablation". I tried this and I can training now.

**Comment by Benwang-chen** [comment]
> I'm not the author, but I solved the problem. The link would be helpful to you: [#16 (comment)](https://github.com/gafniguy/4D-Facial-Avatars/issues/16#issuecomment-1030278405) After doing this, there are no errors related to the ablation study.

I try your solution, but I still have the problem.
