### ISSUE TITLE
IndexError

### ISSUE THREAD

**Issue by wudidecc** [gafniguy/4D-Facial-Avatars#48]
After running train_transformed_rays, there is an error during running eval_transformed_rays:

Traceback (most recent call last):
  File "eval_transformed_rays.py", line 522, in <module>
    main()
  File "eval_transformed_rays.py", line 459, in main
    latent_code = latent_codes[index_of_image_after_train_shuffle].to(device) if use_latent_code else None
IndexError: index 1150 is out of bounds for dimension 0 with size 100

Do you have the idea how to fix this?

Thanks in advance!

**Comment by wuzuyin** [comment]
> After running train_transformed_rays, there is an error during running eval_transformed_rays:
> 
> Traceback (most recent call last): File "eval_transformed_rays.py", line 522, in main() File "eval_transformed_rays.py", line 459, in main latent_code = latent_codes[index_of_image_after_train_shuffle].to(device) if use_latent_code else None IndexError: index 1150 is out of bounds for dimension 0 with size 100
> 
> Do you have the idea how to fix this?
> 
> Thanks in advance!

I have also encountered the same problem. Have you resolved it
