### ISSUE TITLE
How much RAM required for training?

### ISSUE THREAD

**Issue by anthnyprschka** [gafniguy/4D-Facial-Avatars#53]
I am able to set up environment on Windows. Now that I run training I run into this issue:
```
Traceback (most recent call last):
File "F:\4D-Facial-Avatars\nerface_code\nerf-pytorch\train_transformed_rays.py", line 602, in <module>
main()
File "F:\4D-Facial-Avatars\nerface_code\nerf-pytorch\train_transformed_rays.py", line 62, in main
images, poses, render_poses, hwf, i_split, expressions, , bboxs = loadflame_data(
File "F:\4D-Facial-Avatars\nerface_code\nerf-pytorch\nerf\load_flame.py", line 87, in load_flame_data
imgs = (np.array(imgs) / 255.0).astype(np.float32)
numpy.core._exceptions._ArrayMemoryError: Unable to allocate 4.03 GiB for an array with shape (5507, 512, 512, 3) and data type uint8
```

**Comment by BanjiBear** [comment]
@anthnyprschka Dear sir,

My name is Tommy. I am currently exploring this work also on Windows.
I would like to humbly ask how did you cope with the signal.SIGUSR1 in training. As it is solely for Unix system, can you provide hints or modifications you have done to make the code executable?

Thank you so much in advance

**Comment by BanjiBear** [comment]
@anthnyprschka 
Dear sir,
I am currently exploring the work also on Windows.
I ran into the same issue raised by you above. I would like to humbly ask if you could provide any solutions?

Thank you so much in advance

**Comment by BanjiBear** [comment]
I tried to modify line86 in [load_flame.py](https://github.com/gafniguy/4D-Facial-Avatars/blob/f687d3be0b15dc7bdcae0a31cf8935987af6863e/nerface_code/nerf-pytorch/nerf/load_flame.py#L86)
and change the float32 to float16 to reduce memory usage, yet, I further encountered:
Runtimeerror: Found dtype Half but expected Float
